---
- name: Install and Enable/Disable GNOME Shell extensions
  hosts: localhost
  become: yes
  gather_facts: yes

  vars_files:
    - extensions.yml  # Include the extensions configuration file

  tasks:
    - name: Read extensions from file
      set_fact:
        extensions: "{{ lookup('file', 'extensions.yml') | from_yaml }}"

    - name: Get a list of extensions to enable
      set_fact:
        extensions_to_install: "{{ extensions | dict2items | selectattr('value.enabled', 'equalto', true) | map(attribute='key') | list }}"

    - name: Get a list of extensions to disable
      set_fact:
        extensions_to_disable: "{{ extensions | dict2items | selectattr('value.enabled', 'equalto', false) | map(attribute='key') | list }}"

    - name: Install and enable GNOME Shell extensions
      include_role:
        name: "{{ item }}"
      with_items: "{{ extensions_to_install }}"
      
    - name: Disable GNOME Shell extensions
      command: "gnome-extensions disable {{ extensions_to_disable }}"
      become_user: "{{ ansible_env.SUDO_USER }}"
      async: 600
      poll: 0
      ignore_errors: yes
